### ISSUE TITLE
Which one is better?

### ISSUE THREAD

**Issue by John1231983** [WillSuen/NonLocalandSEnet#1]
Senet and NL network. Which one is better in term of accuracy on imagenet and cifar dataset? Thanks

**Comment by WillSuen** [comment]
You can go to read their paper. I think SENet is better on imagenet classification. But NL can be applied to other networks, such as segmentation, GANs

**Comment by John1231983** [comment]
Good point. Actually. I read both papers. I just wonder if you have applied NL for segmentation. Could you share the information the NL can improve performance on segmentation?

**Comment by WillSuen** [comment]
No. I did not apply the NL to segmentation. But in the NL paper, they have applied NL block to Mask-RCNN and get improvement, 1% I think
